apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config-ini
  labels:
    app.kubernetes.io/instance: grafana-ui
data:
  grafana.ini: |
    [server]
      domain = grafana-cluster-ui.centralindia.cloudapp.azure.com
      root_url = https://%(domain)s
    [auth.azuread]
      name = Azure AD
      enabled = true
      allow_sign_up = true
      allowed_domains = soroco.com
      auto_login = false
      scopes = openid email profile offline_access
      role_attribute_strict = false
      allow_assign_grafana_admin = false
      skip_org_role_sync = false
    # Metrics available at HTTP URL /metrics and /metrics/plugins/:pluginId
    [metrics]
    # Disable / Enable internal metrics
    enabled           = true

    # Disable total stats (stat_totals_*) metrics to be generated
    disable_total_stats = false