read:
  replicas: 1
  extraArgs: ["-config.expand-env=true"]
  extraEnv:
    - name: LOKI_BLOB_ACCOUNT_KEY
      valueFrom:
        secretKeyRef:
          name: loki-config-secret
          key: accountKey

write:
  extraArgs: ["-config.expand-env=true"]
  replicas: 1
  extraEnv:
    - name: LOKI_BLOB_ACCOUNT_KEY
      valueFrom:
        secretKeyRef:
          name: loki-config-secret
          key: accountKey

backend:
  extraArgs: ["-config.expand-env=true"]
  replicas: 1
  extraEnv:
    - name: LOKI_BLOB_ACCOUNT_KEY
      valueFrom:
        secretKeyRef:
          name: loki-config-secret
          key: accountKey


gateway:
  service:
    type: LoadBalancer
    annotations: 
      service.beta.kubernetes.io/azure-dns-label-name: grafana-cluster-loki

  basicAuth:
    enabled: true
    existingSecret: loki-htpasswd

monitoring:
  dashboards:
    namespace: grafana-ui
    enabled: true
  rules:
    enabled: true
  serviceMonitor:
    enabled: true
    metricsInstance: 
      enabled: false
    namespaceSelector:
      any: true
    labels:
      instance: primary
  selfMonitoring:
    tenant:
      name: "scout-obs-dev1"

    grafanaAgent:
      installOperator: false
loki:
  limits_config:
    enforce_metric_name: false
    max_cache_freshness_per_query: 10m
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    split_queries_by_interval: 15m
    per_stream_rate_limit: 512M
    cardinality_limit: 200000
    ingestion_burst_size_mb: 1000
    ingestion_rate_mb: 10000
    max_entries_limit_per_query: 1000000
    max_global_streams_per_user: 100000
    max_streams_per_user: 10000
    max_label_value_length: 20480
    max_label_name_length: 10240
    max_label_names_per_series: 300
  auth_enabled: true
  
  commonConfig:
    replication_factor: 1
  commonStorageConfig:
    azure:
      container_name: loki_common
  ruler:
    storage:
      azure:
        container_name: loki_ruler
    type: azure
  schemaConfig:
    configs:
    - from: "2020-12-01"
      index:
        period: 24h
        prefix: loki_index_
      object_store: azure
      schema: v12
      store: boltdb-shipper
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: azure
    azure:
      # use_service_principal: true
      # # Azure tenant ID used to authenticate through Azure OAuth
      # tenant_id : <tenant-id>
      # # Azure Service Principal ID
      # client_id: <client-id>
      # # Azure Service Principal secret key
      # client_secret: <client-secret>
      accountName: "lokigrafanasre"
      accountKey: "${LOKI_BLOB_ACCOUNT_KEY}"
      # See https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#containers
      container_name: lokigrafana
      request_timeout: 0
    boltdb_shipper:
      active_index_directory: /var/loki/data/loki/boltdb-shipper-active
      cache_location: /var/loki/data/loki/boltdb-shipper-cache
      cache_ttl: 24h
      shared_store: azure
    filesystem:
      directory: /var/loki/data/loki/chunks
  compactor:
    working_directory: /var/loki/data/loki/boltdb-shipper-compactor
    shared_store: azure