# apiVersion: grafana.integreatly.org/v1beta1
# kind: GrafanaDatasource
# metadata:
#   name: grafana-datasource-loki
# spec:
#   allowCrossNamespaceImport: true
#   valuesFrom:
#     - targetPath: "user"
#       valueFrom:
#         secretKeyRef:
#           name: "datasource-loki-read-credentials"
#           key: "LOKI_USERNAME"
#     - targetPath: "secureJsonData.password"
#       valueFrom:
#         secretKeyRef:
#           name: "datasource-loki-read-credentials"
#           key: "LOKI_PASSWORD"
#   instanceSelector:
#     matchLabels:
#       dashboards: "grafana"
#   datasource:
#     name: loki
#     access: proxy
#     type: loki
#     basicAuth: true
#     url: http://loki-gateway.loki.svc.cluster.local:80
#     basicAuthUser: ${LOKI_USERNAME}
#     jsonData:
#       httpHeaderName1: X-Scope-OrgID
#     secureJsonData:
#       "basicAuthPassword": ${LOKI_PASSWORD}
#       "httpHeaderValue1": "monitoring-system"
#     editable: true
