apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  project: operators
  source:
    repoURL: ghcr.io/grafana-operator/helm-charts
    chart: grafana-operator
    targetRevision: v5.0.0
    helm:
      releaseName: grafana-operator
  destination:
    namespace: grafana-ui
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent-operator
  namespace: argocd
spec:
  project: operators
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana-agent-operator
    targetRevision: 0.2.15
    helm:
      releaseName: grafana-agent-operator
      valueFiles:
        - values.yaml
      values: |
        image:
          tag: v0.34.1
  destination:
    namespace: grafana-agent
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-operator
  namespace: argocd
spec:
  project: operators
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-metrics-operator
    targetRevision: 0.23.1
    helm:
      releaseName: victoria-metrics-operator
      valueFiles:
        - values.yaml
      values: |
        operator:
          prometheus_converter_add_argocd_ignore_annotations: true
  destination:
    namespace: vm-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crd
  namespace: argocd
spec:
  project: operators
  source:
    repoURL: 'https://github.com/prometheus-operator/prometheus-operator'
    targetRevision: main
    path: 'example/prometheus-operator-crd'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'vm-operator'
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
