apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: grafana
spec:
  ports:
    - port: 3000
      name: http
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
