apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: datasource-vm-system-read
  labels:
    target: vm-system
spec:
  passwordRef:
    name: datasource-vm-system-read-credentials
    key: VM_PASSWORD
  username: vm_system_read_user
  targetRefs:
    - crd:
        kind: VMCluster/vmselect
        name: vm-system
        namespace: vm-system
      paths: ["/.*"]
    - static:
        url: http://vmalert-vm-system-alert.vm-system.svc:8080
      paths: ["/api/v1/groups","/api/v1/alerts"]
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vm-system-push
  labels:
    target: vm-system
spec:
  passwordRef:
    name: vm-system-push-credentials
    key: VM_PASSWORD
  username: vm_system_push_user
  targetRefs:
    - crd:
        kind: VMCluster/vminsert
        name: vm-system
        namespace: vm-system
      paths: ["/.*"]
    - static:
        url: http://vmalert-vm-system-alert.vm-system.svc:8080
      paths: ["/api/v1/groups","/api/v1/alerts"]