apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-ui
  namespace: argocd
spec:
  project: monitoring-system
  source:
    repoURL: 'https://dev.azure.com/SorocoProducts/Scout/_git/MonitoringPlatformGitOps'
    targetRevision: develop
    path: configs/monitoring-system/grafana-ui
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana-ui
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
